name: CI BookService

on:
  push:

  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1
      - name: Install maven and jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
      - name: Build app
        run: mvn clean install
      - name: Validate compile object    
        run: ls -l target/

        